# Dictionaries

In [2]:
dict = {"Key":"value"}

In [3]:
dict

{'Key': 'value'}

In [4]:
dict.keys

<function dict.keys>

In [5]:
dict.keys()

dict_keys(['Key'])

In [6]:
dict.values()

dict_values(['value'])

In [12]:
dict["Key"] = "Hello"
dict

{'Key': 'Hello'}

In [15]:
dict["Key"]

'Hello'

# DataFrames

In [23]:
import pandas as pda

In [29]:
stateInfo = {'Colorado': 
            {'Population': 5812000,
            'Capital': 'Denver',
            'Founded': 'Feb. 28, 1861'},
             
            'North Dakota':
            {'Population':774948,
            'Capital':'Bismarck',
            'Founded': 'Nov. 2, 1889'}}
stateInfo = pd.DataFrame(stateInfo).T #transpose, evaluate as DataFrame and assign to variable

In [28]:
stateInfo

Population   Capital        Founded
Colorado        5812000    Denver  Feb. 28, 1861
North Dakota     774948  Bismarck   Nov. 2, 1889

In [30]:
stateInfo.to_excel("Chapter_3_in_class.xls")

# Introduction to _numpy_, _pandas_, and _matplotlib_

In addition to lists and dictionaries, there exists data structures from the numpy and pandas libraries that you should be aware of. The numpy library uses structures that are more efficient than dynamic lists. Pandas, which uses numpy, helps to organize data in tables. Dataframes from pandas can also be used to make data visualization in matplotlib a breeze.

## numpy

| New Concepts | Description |
| --- | --- |
| _numpy_ | The numpy package provides data structures including arrays and linear algebra matrices, as well as  efficient calculation processes. |
| _numpy_ methods | np.array(), np.arange(), np.zeros(), np.ones(), np.zeros_like(), np.ones_like(), np.empty_like() | 
| two-dimensional lists and arrays | Lists that hold other lists and arrays that hold other arrays are multi-dimensional. We will work with two dimensional arrays in this section.|

### Arrays

Lists in Python do not need to be cast a particular type of object such as float, string, or object. This makes programming in Python relatively simple. Lists in Python are dynamic, meaning that they are not fixed in size. This comes with the drawback that execution time is slower than it otherwise could be. 

Although it is a library in Python, numpy functions are programmed in C++. The numpy library solves this problem by creating arrays that contain data types that are values. These include integers and a variety of floats. Both of these aspects contribute to a substantial increase in efficiency for computation performed using numby arrays instead of dynamic lists. 

There are a number of ways to create a numpy array. The easiest is simply to convert a python list using the command array. 

In [1]:
import numpy as np

In [2]:
numpyarray = np.array([1,2,3,4,5])
print(numpyarray)

[1 2 3 4 5]


In [3]:
numpyarray.dtype()

TypeError: 'numpy.dtype' object is not callable

In [4]:
numpyarray.dtype

dtype('int32')

In [7]:
numpyarray

array([1, 2, 3, 4, 5])

In [10]:
numpyarray.loc[1] = 2.0

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [11]:
numpyarray = np.array([1,2.,3,4,5])

In [13]:
numpyarray

array([1., 2., 3., 4., 5.])

In [14]:
numpyarray.dtype

dtype('float64')

# Make an array quickly with Numpy

use np.arange(start, end+1, interval)

In [15]:
numpyarray = np.arange(0,100, 1.098238)

In [17]:
len(numpyarray)

92

In [18]:
numpyarray = np.arange(0,100, 1)

In [19]:
numpyarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
len(numpyarray)

100

In [22]:
numpyarray = np.arange(1,101,1)
numpyarray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
len(numpyarray)

100

# Dimensional arrays

In [43]:
twodee = [['x-axis','y-axis', 'z-axis'],[1,2,3]]

In [25]:
twodee

[['x-axis', 'y-axis', 'z-axis'], [1, 1, 1]]

Read this assignment as follows:
twodee get two lists, one for axes, second for value. Each list contains three values

In [31]:
for i in range((len(twodee))):
    print(twodee[i])
    
print(twodee[0],twodee[1])

['x-axis', 'y-axis', 'z-axis']
[1, 1, 1]
['x-axis', 'y-axis', 'z-axis'] [1, 1, 1]


'For each object in twodee, print the object. Before printing the next object, print the objects within that object' -- see below

In [44]:
for i in range((len(twodee))):
    print("This is the object " + str(i))
    for j in range(len(twodee[i])):
        print('this is object ', str(i), ':', twodee[i][j])

This is the object 0
this is object  0 : x-axis
this is object  0 : y-axis
this is object  0 : z-axis
This is the object 1
this is object  1 : 1
this is object  1 : 2
this is object  1 : 3
